### ISSUE TITLE
design Front HTML

### ISSUE THREAD

**Issue by aaguirre7** [aaguirre7/my_crypto#7]
design site HTML and look.
make sure is responsive!!!

**Comment by MaxKarltun** [comment]
LEFT TO PUSH LATEST index.HTML to the project. one all parties agree to the design we will push the code back up.
HTML, and CSS are now complete for the moment until later add on and extra syntex clean ups.
looks like a good start now we have to make the LOGIN AND USERNAME WORK. The My Crypto logo is position center top.
Login Form finished being built and soon to fully operate.
Design textures implemented with CSS complete.

**Comment by aaguirre7** [comment]
please always push
